name: 'Push to Lokalise'
description: 'Push translation files to Lokalise'
author: 'Lokalise Team'
inputs:
  lokalise_api_token:
    description: 'API token for Lokalise with read/write permissions'
    required: true
    secret: true
  lokalise_project_id:
    description: 'Project ID for Lokalise'
    required: true
  lokalise_source_lang:
    description: 'Source language (e.g., en, fr_FR)'
    required: true
    default: 'en'
  lokalise_translations_path:
    description: 'Path to translation files'
    required: true
    default: 'locales'
  lokalise_file_format:
    description: 'Format of the translation files (e.g., json)'
    required: true
    default: 'json'
  lokalise_push_additional_params:
    description: 'Additional parameters for Lokalise CLI push'
    required: false

runs:
  using: 'bash'
  main: 'entrypoint.sh'

# branding:
#   icon: 'upload'
#   color: 'blue'
