name: 'Push to Lokalise'
description: 'Push translation files to Lokalise'
author: 'Lokalise Team'
inputs:
  api_token:
    description: 'API token for Lokalise with read/write permissions'
    required: true
    secret: true
  project_id:
    description: 'Project ID for Lokalise'
    required: true
  base_lang:
    description: 'Base language (e.g., en, fr_FR)'
    required: true
    default: 'en'
  translations_path:
    description: 'Path to translation files'
    required: true
    default: 'locales'
  file_format:
    description: 'Format of the translation files (e.g., json)'
    required: true
    default: 'json'
  additional_params:
    description: 'Additional parameters for Lokalise CLI on push'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: "${{ inputs.translations_path }}/${{ inputs.base_lang }}/**.${{ inputs.file_format }}"

    - name: Install Lokalise CLI
      if: steps.changed-files.outputs.any_changed == 'true'
      shell: bash
      run: |
        if [ ! -f ./bin/lokalise2 ]; then
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh || {
            echo "Failed to install Lokalise CLI"
            exit 1
          }
        else
          echo "Lokalise CLI already installed, skipping installation."
        fi

    - name: Push translation files to Lokalise
      if: steps.changed-files.outputs.any_changed == 'true'
      shell: bash
      env:
        LOKALISE_TOKEN: ${{ inputs.api_token }}
        CLI_ADD_PARAMS: ${{ inputs.additional_params }}
        BASE_LANG: ${{ inputs.base_lang }}
      run: |
        ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"

        chmod +x "${{ github.action_path }}/../../src/scripts/lokalise_upload.sh"

        echo "$ALL_CHANGED_FILES" | tr ' ' '\n' | xargs -P 6 -I {} bash -c '. "${{ github.action_path }}/../../src/scripts/lokalise_upload.sh" && upload_file "$@"' _ "{}" "${{ inputs.project_id }}"

        if [ $? -ne 0 ]; then
          echo "File upload failed"
          exit 1
        fi
