name: 'Push to Lokalise'
description: 'Push translation files to Lokalise'
author: 'Lokalise Team'
inputs:
  lokalise_api_token:
    description: 'API token for Lokalise with read/write permissions'
    required: true
    secret: true
  lokalise_project_id:
    description: 'Project ID for Lokalise'
    required: true
  lokalise_source_lang:
    description: 'Source language (e.g., en, fr_FR)'
    required: true
    default: 'en'
  lokalise_translations_path:
    description: 'Path to translation files'
    required: true
    default: 'locales'
  lokalise_file_format:
    description: 'Format of the translation files (e.g., json)'
    required: true
    default: 'json'
  lokalise_push_additional_params:
    description: 'Additional parameters for Lokalise CLI push'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: "${{ inputs.lokalise_translations_path }}/${{ inputs.lokalise_source_lang }}/**.${{ inputs.lokalise_file_format }}"

    - name: Install Lokalise CLI
      if: steps.changed-files.outputs.any_changed == 'true'
      shell: bash
      run: |
        if [ ! -f ./bin/lokalise2 ]; then
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh || {
            echo "Failed to install Lokalise CLI"
            exit 1
          }
        else
          echo "Lokalise CLI already installed, skipping installation."
        fi

    - name: Push Localization Files to Lokalise
      if: steps.changed-files.outputs.any_changed == 'true'
      shell: bash
      env:
        LOKALISE_API_TOKEN: ${{ inputs.lokalise_api_token }}
        LOKALISE_PROJECT_ID: ${{ inputs.lokalise_project_id }}
        LOKALISE_SOURCE_LANG: ${{ inputs.lokalise_source_lang }}
        LOKALISE_TRANSLATIONS_PATH: ${{ inputs.lokalise_translations_path }}
        LOKALISE_FILE_FORMAT: ${{ inputs.lokalise_file_format }}
        LOKALISE_CLI_ADD_PARAMS: ${{ inputs.lokalise_push_additional_params }}
        ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
      run: |
        ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"

        chmod +x "${{ github.action_path }}/../../src/scripts/lokalise_upload.sh"

        echo "$ALL_CHANGED_FILES" | tr ' ' '\n' | xargs -P 6 -I {} bash -c '. "${{ github.action_path }}/../../src/scripts/lokalise_upload.sh" && upload_file "$@"' _ "{}" "${{ inputs.lokalise_project_id }}" "${{ inputs.lokalise_source_lang }}"

        if [ $? -ne 0 ]; then
          echo "File upload failed"
          exit 1
        fi
