name: Push to Lokalise but old
run-name: Push to Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
      VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
      VAR_LOKALISE_SOURCE_LANG_ISO: ${{ vars.SOURCE_LANG }}
      VAR_FOLDER_PATH: ${{ vars.FOLDER_PATH }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history of the repository to ensure all commits are available

      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      - name: Determine upstream branch
        id: determine-branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ -n "${{ github.event.pull_request.base.ref }}" ]]; then
              echo "${{ github.event.pull_request.base.ref }}" > upstream_branch.txt
            else
              echo "${{ github.event.repository.default_branch }}" > upstream_branch.txt
            fi
          else
            echo "${{ github.event.repository.default_branch }}" > upstream_branch.txt

      # - name: Get changed JSON files
      #   id: get-changed-files
      #   run: |
      #     UPSTREAM_BRANCH=$(cat upstream_branch.txt)
      #     echo "Upstream Branch: $UPSTREAM_BRANCH"
      #     git fetch origin $UPSTREAM_BRANCH
      #     if [ "${{ github.ref_name }}" = "${{ github.repository_default_branch }}" ]; then
      #       git diff --name-only HEAD~1 HEAD -- "${{ env.VAR_FOLDER_PATH }}/${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}/**.json" > changed_files.txt
      #     else
      #       git diff --name-only origin/$UPSTREAM_BRANCH...HEAD -- "${{ env.VAR_FOLDER_PATH }}/${{ env.VAR_LOKALISE_SOURCE_LANG_ISO }}/**.json" > changed_files.txt

      # - name: Upload Changed Files Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: changed-files
      #     path: changed_files.txt

      # - name: Download Changed Files Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: changed-files

      # - name: Print Changed Files
      #   run: |
      #     echo "Changed JSON files:"
      #     cat changed_files.txt

      # - name: Check for Changed Files
      #   run: |
      #     if [ ! -s changed_files.txt ]; then
      #       echo "No JSON files changed."
      #       exit 0

      # - name: Push Localization Files to Lokalise
      #   run: |
      #     chmod +x ./upload_to_lokalise.sh
      #     cat changed_files.txt | xargs -P 6 -I {} bash -c './upload_to_lokalise.sh upload_file "{}"'
