name: Push to Lokalise
run-name: Push to Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:
  # Uncomment to run on PR merge:
  # pull_request_target:
  #   types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOKALISE_SOURCE_LANG: ${{ vars.LOKALISE_SOURCE_LANG }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v44
        env:
          LOKALISE_FILE_FORMAT: ${{ vars.LOKALISE_FILE_FORMAT }}
          LOKALISE_TRANSLATIONS_PATH: ${{ vars.LOKALISE_TRANSLATIONS_PATH }}
        with:
          files: "${{ env.LOKALISE_TRANSLATIONS_PATH }}/${{ env.LOKALISE_SOURCE_LANG }}/**.${{ env.LOKALISE_FILE_FORMAT }}"

      - name: Install Lokalise CLI
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          if [ ! -f ./bin/lokalise2 ]; then
            curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh || {
              echo "Failed to install Lokalise CLI"
              exit 1
            }
          else
            echo "Lokalise CLI already installed, skipping installation."
          fi
        
      - name: Push Localization Files to Lokalise
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
          LOKALISE_CLI_ADD_PARAMS: ${{ vars.LOKALISE_PUSH_ADDITIONAL_PARAMS }}
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ vars.LOKALISE_PROJECT_ID }}
        run: |
          upload_file() {
            local file=$1
            local attempt=0
            local max_retries=3
            local sleep_time=1

            # Check if LOKALISE_CLI_ADD_PARAMS is set and not empty
            if [ -n "${LOKALISE_CLI_ADD_PARAMS}" ]; then
              additional_params="${LOKALISE_CLI_ADD_PARAMS}"
            else
              additional_params=""
            fi

            echo "Starting upload for $file"
            while [ $attempt -lt $max_retries ]; do
              output=$(./bin/lokalise2 --token="${LOKALISE_API_TOKEN}" \
                --project-id="${LOKALISE_PROJECT_ID}" \
                file upload \
                --file="$file" \
                --lang-iso="${LOKALISE_SOURCE_LANG}" \
                --replace-modified \
                --include-path \
                --distinguish-by-file \
                --poll \
                --poll-timeout=120s \
                --tag-inserted-keys \
                --tag-skipped-keys=true \
                --tag-updated-keys \
                --tags "$GITHUB_REF_NAME" \
                $additional_params 2>&1)

              if echo "$output" | grep -q 'API request error 429'; then
                attempt=$((attempt + 1))
                echo "Attempt $attempt failed with API request error 429. Retrying in $sleep_time seconds..."
                sleep $sleep_time
                sleep_time=$((sleep_time * 2))
              elif echo "$output" | grep -q 'API request error'; then
                echo "Permanent error encountered during upload: $output"
                return 1
              else
                echo "Successfully uploaded file: $file"
                return 0
              fi
            done

            echo "Failed to upload file: $file after $max_retries attempts"
            return 1
          }

          export -f upload_file
          echo "${ALL_CHANGED_FILES}" | tr ' ' '\n' | xargs -P 6 -I {} bash -c 'upload_file "$@"' _ {}
          result=$?
          if [ $result -ne 0 ]; then
            echo "Error during file upload with exit code $result"
            exit $result
          fi
